modelflow_ai:
    providers:
        openai:
            enabled: true
            credentials:
                api_key: '%env(OPENAI_API_KEY)%'
        ollama:
            enabled: true

    adapters:
        gpt4o:
            enabled: true
        llama3_2:
            enabled: true
